[package]
name = "kernel"
version = "0.1.0"
edition = "2021"
authors = ["Qin-shihuang <0.0@owo.li>"]

[dependencies]
allocator = { path = "../crates/allocator" }
sbi = { path = "../crates/sbi" }

log = "0"